site_name: 郝鑫磊的技术笔记
site_description: Java 后端 & 大模型开发学习笔记
site_author: cowfat97
site_url: https://cowfat97.github.io/notes/
docs_dir: "."

theme:
  name: material
  language: zh
  features:
    - navigation.tracking
    - search.highlight

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - tables

nav:
  - 首页: README.md
  - Java:
      - Java/Java 基础/
      - Java/JVM/
      - Java/多线程/
      - Java/集合/
  - 中间件:
      - 中间件/Redis/
      - 中间件/Nginx/
  - 数据库:
      - 数据库/Mysql/
  - LLM:
      - LLM/Rag/RAG.md
  - 408:
      - 408/数据结构/
  - LeetCode: leetcode/
