site_name: 郝鑫磊的技术笔记
site_description: Java 后端 & 大模型开发学习笔记
site_author: cowfat97
docs_dir: "."

theme:
  name: material
  language: zh
  features:
    - navigation.tracking
    - search.highlight

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - tables

nav:
  - 首页: README.md
  - Java:
      - Java/Java 基础/
      - Java/JVM/
      - Java/多线程/
      - Java/框架/
      - Java/集合/
  - 中间件:
      - 中间件/Redis/
      - 中间件/Kafka/
      - 中间件/Nginx/
      - 中间件/Docker/
      - 中间件/Nacos/
  - 数据库:
      - 数据库/Mysql/
  - LLM:
      - LLM/Rag/RAG.md
      - LLM/Agent/
  - 408:
      - 408/数据结构/
      - 408/计算机组成原理/
      - 408/操作系统/
      - 408/计算机网络/
  - LeetCode: leetcode/
