site_name: Notes

nav:
  - Home: README.md
  - Java:
      - Overview: Java/README.md
  - 中间件:
      - Overview: 中间件/README.md
  - 数据库:
      - Overview: 数据库/README.md
  - LLM:
      - Overview: LLM/README.md
  - 408:
      - Overview: 408/README.md
  - leetcode:
      - Overview: leetcode/README.md
  - 软考:
      - Overview: 软考/README.md
